### ISSUE TITLE
Runner should scale only if workflow of check event is queued

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#14]
Currently the runner scales at the moment any workflow in the repo that sends the event is in the status queued. This should be if the workflow correleated tot the received event.

**Comment by leoblanc** [comment]
@npalm Hi Niek, a question that maybe is related to this issue. We have a repo with several GitHub pipelines. Most of them are configured to be executed in the cloud. Only a few include `runs-on: self-hosted`. We did some tests and it seems like too many runners are created (scale-up) at the same time (much more than the number required by the self-hosted pipelines). Is that behavior the same problem described by this issue? Otherwise, any ideas of what could be happening? Thanks in advance!

**Comment by npalm** [comment]
Yes sounds like related. Would be great if we can find a better option to scale. Currently each check event is sent to the webhook. After delaying for 30 seconds on a queue, the scale up lambda kicks in. The lambda check is any queued build for that repo. So not even the build that generated the event. In case builds are queued in creates a runner and done. We assume the build we be picked up some time later. For us, on org level, it works quite good. 

Any good suggestion is more welcome to improve this behavior to a more efficient way.

**Comment by leoblanc** [comment]
Thanks for your info. When you say "each check event is sent to the webhook" you are talking about "[check runs](https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#check-runs)" right? 

I'm not very familiar with GitHub API but what I understand is this: every time a developer pushes code, that event is triggered (and forwarded to the webhook and then queued). Then, the terraform-aws-github-runner module creates a runner for each queue item. 

Am I correct? Thanks again.

**Comment by npalm** [comment]
Would be nice if GitHub can provide events for jobs including information of the runner selector. For the time being the only good option seems to scale based on the `check_run` event. With fix #423 we scale only of the event received via SQS has still a queued build. Not for any queued build in the repo.
