### ISSUE TITLE
docker.sock: connect: permission denied when runner attempts to pull image on Ubuntu/AWS

### ISSUE THREAD

**Issue by MRostanski** [philips-labs/terraform-aws-github-runner#1844]
Hi,
I am using version "0.36" and follow the example in https://github.com/philips-labs/terraform-aws-github-runner/tree/develop/examples/ubuntu

## Problem

Everything sets up nicely, however when runner is executing a job that involves actions, the first task is to pull images and I am struggling with the following:
```
Pull down action image 'bridgecrew/checkov:2.0.941'
  /home/runners/bin/docker pull bridgecrew/checkov:2.0.941
  Got permission denied while trying to connect to the Docker daemon socket at unix:///run/user/1001/docker.sock: Post "http://%2Frun%2Fuser%2F1001%2Fdocker.sock/v1.24/images/create?fromImage=bridgecrew%2Fcheckov&tag=2.0.941": dial unix /run/user/1001/docker.sock: connect: permission denied
```

Of course Checkov is just an example of legit working GH action and a docker image, verified and checked to be working elsewhere.

## Notes:

I have tried adding the following to the template script:

* `setfacl --modify user:$USER_ID:rw /run/user/$USER_ID/docker.sock` - no effect
* `usermod -a -G docker $USER_NAME` - no effect

However, when I check the `id` in the pipeline, it does not use the `runners` user, but `ubuntu`. I think the issue comes from somewhere here:

```
Run echo $(id)
uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),117(netdev),118(lxd),1002(docker)
```
(but if you think of debugging with something like `setfacl --modify user:ubuntu:rw /run/user/$USER_ID/docker.sock`, it still brings no effect.
Please advise on possible solutions. I'd be happy to test anything.

**Comment by tymofii-okh** [comment]
Hi!
I think the fix would be to set `runner_run_as = "runners"` here https://github.com/philips-labs/terraform-aws-github-runner/blob/819fa4f16996ff4176d7f16f3ded06f0099a8135/examples/ubuntu/main.tf#L40
and add `user_name=$USER_NAME` here https://github.com/philips-labs/terraform-aws-github-runner/blob/819fa4f16996ff4176d7f16f3ded06f0099a8135/examples/ubuntu/templates/user-data.sh#L61
before `${install_runner}` as it is done here https://github.com/philips-labs/terraform-aws-github-runner/blob/819fa4f16996ff4176d7f16f3ded06f0099a8135/modules/runners/templates/user-data.sh#L15

The problem is that it runs with an `ubuntu` user instead of a `runners` user.

**Comment by d-olivas** [comment]
> Hi! I think the fix would be to set `runner_run_as = "runners"` here
> 
> https://github.com/philips-labs/terraform-aws-github-runner/blob/819fa4f16996ff4176d7f16f3ded06f0099a8135/examples/ubuntu/main.tf#L40
> 
> 
> and add `user_name=$USER_NAME` here
> https://github.com/philips-labs/terraform-aws-github-runner/blob/819fa4f16996ff4176d7f16f3ded06f0099a8135/examples/ubuntu/templates/user-data.sh#L61
> 
> 
> before `${install_runner}` as it is done here
> https://github.com/philips-labs/terraform-aws-github-runner/blob/819fa4f16996ff4176d7f16f3ded06f0099a8135/modules/runners/templates/user-data.sh#L15
> 
> The problem is that it runs with an `ubuntu` user instead of a `runners` user.

I had this same issue and solved it. But I changed this line to be "ubuntu" instead of "runners" and left `runner_run_as: "ubuntu" as it is`:
https://github.com/philips-labs/terraform-aws-github-runner/blob/819fa4f16996ff4176d7f16f3ded06f0099a8135/examples/ubuntu/templates/user-data.sh#L18

Thank you @tymofii-okh !
