### ISSUE TITLE
Allow userdata to be passed as a string

### ISSUE THREAD

**Issue by rashidnhm** [philips-labs/terraform-aws-github-runner#1960]
# Overview of the Issue
Currently the module allows the userdata set on the aws_launch_template to be overriden if the variable [userdata_template](https://github.com/philips-labs/terraform-aws-github-runner#input_userdata_template) is passed. However, that variable currently only accepts *path to a userdata script* as the value of it is passed to `templatefile` [here](https://github.com/philips-labs/terraform-aws-github-runner/blob/58bfec0f1a3ee7a55054f1e7ebd77e0ee156c04a/modules/runners/main.tf#L119). 

It would be good to have a way to pass the userdata script as a string itself rather than a path to a file.

# Motivation for or Use Case
I ran into this issue while attempting to setup multiple runners on the same instance. I have my own scripts that are loaded and rendered through `templatefile` that I want to pass as userdata to the module.

However, I am not finding any straightforward way of doing this, the only way I can currently do it is:
- Pre-built AMI
- Somehow generate a local temp file and pass the location of that. Terraform currently does not support the creation of temp file (being tracked at hashicorp/terraform#21308). And I do not want to use the local provider to create files as there would be a diff in the plan depending on where the module is being called from.

# Module version being used
0.40.0

# Suggest a Fix
A fix would be to introduce another variable with would allow the user to pass the userdata script as a string instead of a path to a file.

**Comment by ScottGuymer** [comment]
The main reason that we use `templatefile` is to provide hooks for the module to replace some values within the file using templating syntax. This means we can merge in important values to the userdata and not have to rely on them being hardcoded into custom userdata.

You can see the values being passed here https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runners/main.tf#L119

Im not sure the same is possible for a string value.

I think it might be possible to just take a string value here and override this whole section, but would be an 'advanced' configuration that would need quite some knowledge on how the module works and what values are needed.

We have been working to move the config external to the userdata script so that it is retrieved from tags or SSM config so that there is less need to replace values in the userdata. This may be a better way forward as adding extra configuration to SSM can be done outside of the module and the userdata script can refer to them.

You can see this approach here https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runners/templates/start-runner.sh#L23

It would be much better to remove the need to use template file at all for the future if we can.

**Comment by rashidnhm** [comment]
I completely agree with in the sense that it is an advanced usecase. As I've state in description of the issue, I am trying to create userdata script with `templatefile` myself and pass that on to module. 

As with the case with the existing `userdata_template`, it would be fair assumption that if the calling module is setting these variables then it is a risk they take on their own to install everything using their own script.

Please see #1963 that I've opened for this issue. It attempts to solve the issue exactly how you defined it where the user can pass the userdata as string and it overrides the whole section (again, similar behavior to the existing `userdata_template` variable ... except instead of passing a path to a script it open the door to pass the script itself as string)
