### ISSUE TITLE
Labelling runners by EC2 instance type

### ISSUE THREAD

**Issue by pfnsec** [philips-labs/terraform-aws-github-runner#2304]
We're interested in the possibility of labelling runners within a group based on their EC2 instance type. 
For example, being able to use the module with:
`instance_types = ["m5.2xlarge", "c5.large"]`
And selector:
`    runs-on: [self-hosted, m5.2xlarge]`

Reading [runners.ts](https://github.com/philips-labs/terraform-aws-github-runner/blob/e2f9a2764f3c404cd2f8649db64253c9e886e2e7/modules/runners/lambdas/runners/src/aws/runners.ts#L31) it appears that the same set of labels are passed to the runner instances regardless of type. 

Can you advise on whether implementing this is feasible? We are exploring workarounds in `user-data.sh` if not.

Thanks!

**Comment by TechDawg270** [comment]
we have a use-case where we are attempting to use multiple combinations of a given instance type and label selector for builds to have the ability to run a certain instance type based on label selector; i.e.

```
runner_extra_labels = "ec2-development"
instance_types.        = ["m6i.xlarge", "m6id.xlarge"]
```
and
```
runner_extra_labels = "ec2-development-perf"
instance_types         = ["r5.2xlarge", "r5.xlarge"]
```
due to this not being defined by a map object we have to instantiate the module twice with each of the settings you see above defined in each individual module block

**Comment by TechDawg270** [comment]
you can achieve this functionality using a map and `for_each`; [see this post](https://github.com/philips-labs/terraform-aws-github-runner/issues/2306#issuecomment-1205186216)
