### ISSUE TITLE
Release 1.9.1 - After deploying latest module version and lambdas labels are not being properly filtered.

### ISSUE THREAD

**Issue by bicefalo** [philips-labs/terraform-aws-github-runner#2452]
I have updated the module and the lambdas to the latest version (1.9.1) for the two module deployments that I have (Infra and QA) and now the checking of the extra labels are not happening in the webhook lambda and every time I run a job that is supposed to be just executed in the QA or Infra the request is passing in both webhooks. Looks like there is something wrong with the new lambda release.

I already have defined the proper values for this:
runner_enable_workflow_job_labels_check to true
runner_enable_workflow_job_labels_check_all to true
for the QA module:
runner_extra_labels = "${var.aws_env},qa"
For the Infra module:
runner_extra_labels = "${var.aws_env}".

For the workflow files:
QA:
runs-on: [self-hosted, linux, x64, "${{ needs.set_vars.outputs.environment_name }}", qa]
Infra:
runs-on: [self-hosted, linux, x64, "${{ needs.set_vars.outputs.environment_name }}"]

**Comment by npalm** [comment]
As far I can see we had no changes in this code.

**Comment by bicefalo** [comment]
Looking into the changelog for the module I have found the reason why is this happening. 
https://github.com/philips-labs/terraform-aws-github-runner/commit/6d9116fe9a8b8620691d4af8aa6c6d6e0003b502

This change broke the way we were handling the splitting of the runners for different purposes, I suspect that is the reason why this parameter was introduced runner_enable_workflow_job_labels_check_all but seems that is not making the proper effect in the code.

**Comment by npalm** [comment]
I think we still have to find a better way on how we handle incoming event in respect to labes. We also looking on a way to support different type of runners. Which will be closely connected to the way which labels will be accepted and which not. Currently we use strict selection, matching all labes. By having a pool for ephemeral runners we ensure we got all jobs processed.

**Comment by npalm** [comment]
In case the workflows are in the same repo, or repo's can access the same runners via the runner groups. You can not rely based on the labels on which runner the job will run

```QA:
runs-on: [self-hosted, linux, x64, "${{ needs.set_vars.outputs.environment_name }}", qa]
Infra:
runs-on: [self-hosted, linux, x64, "${{ needs.set_vars.outputs.environment_name }}"]
```

Your job for infra can also run on your QA runner based on the labels, since the labels specified will also match the QA runner. This means if both runners are running it is just a lottery which will take the job. The module is using the events to create runners. Once the runner is up, it is GitHub that select the jobs. Nothing we can do. For this reason the changes you mentioned was made. I think the only option you have is to add an extra label for infra

**Comment by npalm** [comment]
We are working on a multi runner option, maybe that can hellp as well. Checkout #2472
