### ISSUE TITLE
Lambda scale up does not start instance when action contains approval environment protection rule

### ISSUE THREAD

**Issue by guilhermeblanco** [philips-labs/terraform-aws-github-runner#2454]
Part of our continuous delivery deployment pipeline consists in an approval step (done via protection rule in the Github repository environment) before effectively deploying our service.

When the workflow_run event is triggered, the status is "waiting" (instead of "queued") and the isJobQueued replies that it will not scale up. It can stay in that status for up to 

This API provides information about pending approval actions: https://docs.github.com/en/rest/actions/workflow-runs#get-pending-deployments-for-a-workflow-run
This API provides information about approving/rejecting a pending action: https://docs.github.com/en/rest/actions/workflow-runs#review-pending-deployments-for-a-workflow-run
Finally, this API details status and conclusion values: https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs-for-a-repository

**Comment by npalm** [comment]
We haven't seen this issue, but we run on quite a scale with a pool. I was expecting that once the approval is done a workflow_job event was fired. Can you double check this event is not fired? You can see all the events sent by the App in one of the detail pages.

**Comment by preipke** [comment]
We are experiencing the same issue. Upgrading to the latest version did not resolve it. It seems that deployments that have to be approved by manual reviews do not trigger runner scale-ups at all. This a real issue to us at the moment and we need to implement some undesired workarounds.

We were using manual deployments for a while already. However, the issue did not occur frequently but only every now and then. We were not able to identify why. Now that we control most of our deployments manually we noticed that runners are not being scaled up at all. 
As long as there are still a couple of continuous deployments that can scale up runners, things are fine because those are unblocking all the manual deployments that will then use the same runners. However, without continuous deployments...

**Comment by guilhermeblanco** [comment]
@npalm Event is not fired, and I can explain a bit more why.

When you have an approval step, the `workflow_job` event contains a status `waiting` instead of `queued`. The scale-up lambda is triggered after and checks for the status right here https://github.com/philips-labs/terraform-aws-github-runner/blob/0c270c6d03b4a768dfebaf9f97e7029e5d4e3056/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts#L106 . Because the status is not queued, message is discarded (it skips the createRunner sequence here https://github.com/philips-labs/terraform-aws-github-runner/blob/0c270c6d03b4a768dfebaf9f97e7029e5d4e3056/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts#L194 ).

When the approval happens, this can be done through Github UI or through API (https://docs.github.com/en/rest/actions/workflow-runs#review-pending-deployments-for-a-workflow-run). The event triggered upon approval/rejection is not the `workflow_job`, but rather a `workflow_run` event (at least this is my suspect). This system only checks for `workflow_job`.

I will attempt to switch to `check_run` event (being promoted as not the legacy solution) sometime soon, but no plans to do it this week. In the meantime, it made sense to report it here, so other people would be aware and maintainers could potentially address it.

**Comment by npalm** [comment]
I would expect for every job a workflow_job event. The check_run will most likely work, you will get normally to many jobs. That is one of the reason why jobs are delayed on the queue and the status check was done. 

In your GitHub app on the advanced tab you can see all the events sent to the webhook. That are the events for which tha app is subscribed. Can you check which events you see once approving the job?
