### ISSUE TITLE
Ephemeral scale up fails occasionally due to misbehaviour on the job queued status check

### ISSUE THREAD

**Issue by vascoalramos** [philips-labs/terraform-aws-github-runner#2459]
We are currently trying to setup our autoscaling self-hosted runners using the ephemeral approach. The runners scale up and down fine. However, when there are several jobs launched simultaneously some of them are never executed because an instance was never launched to them, meaning it was launched fewer instances than needed.

We found out this was happening because there seems to be some misbehavior with the `queued` status check. What happens is that some jobs fail in this verification even though, as far as we could see, they already had the `queued` status on the GitHub Webhook Page when the verification is executed. Also, by disabling the flag associated with this validation (i.e. setting `enable_job_queued_check = false`), the problem doesn't seem to happen.

We tried multiple `delay_webhook_event` values (0, 60, 120, 180, and also de default 30) and every time the problem occurred consistently, as can be seen in the snippet below and the image from the GitHub Hooks Page (the job was queued prior to the validation).

```
2022-09-26 10:41:18.842  INFO  [scale-up:2481c669-49b2-5161-ab12-9dc2ca482740 index.js:113479  isJobQueued] Job not queued 
{
    "runnerType": "Org",
    "runnerOwner": "myorg",
    "event": "workflow_job",
    "id": "8548014748"
}
```
![image](https://user-images.githubusercontent.com/38591616/192289446-c41ddb13-fc84-4b36-8cdc-59560f6371d6.png)

**Version:** 1.9.1
**Configuration**:
- Custom prebuilt based on AWS AMI `ubuntu-jammy-22.04-amd64-server`

Overall configuration below:

```terraform
module "aws-github-runner" {
  source  = "philips-labs/github-runner/aws"
  version = "1.9.1"

  prefix = local.name

  create_service_linked_role_spot = true
  aws_region                      = local.region
  vpc_id                          = module.vpc.vpc_id
  subnet_ids                      = module.vpc.private_subnets

  github_app = {
    key_base64     = local.github_app_private_key_base64
    id             = local.github_app_id
    webhook_secret = local.github_webhook_secret
  }

  webhook_lambda_zip = "${path.module}/src/lambda-functions/webhook.zip"
  runners_lambda_zip = "${path.module}/src/lambda-functions/runners.zip"

  enable_organization_runners   = true
  enable_ephemeral_runners      = true
  enable_runner_binaries_syncer = false
  enable_job_queued_check       = true
  enable_ssm_on_runners         = true

  runner_extra_labels = "default,example"
  runner_os           = local.runner_os
  runner_run_as       = local.runner_username
  enabled_userdata    = false

  ami_filter = {
    name = [
      local.ami_name_filter
    ]
  }

  ami_owners = [
    data.aws_caller_identity.current.account_id
  ]

  runner_enable_workflow_job_labels_check = true

  runners_maximum_count = 20
  instance_types = [
    "m5.large"
  ]

  delay_webhook_event             = 0 # we tried other values also
  scale_down_schedule_expression  = "cron(* * * * ? *)"

  log_level = "debug"

  tags = local.tags

  depends_on = [
    packer_image.build_custom_ami
  ]
}
```

Could you please let me know if this is indeed a bug or misconfiguration on our side?
Also, let me know if more information is required.

**Comment by npalm** [comment]
Using ephemeral runners there is a catch. The module should try to create a runner for each received event that is accepted by the webhook. Accepted means the right labels and status queued. Next the scale up lambda will create a runner, which could fail. In case the failure looks a recoverable one the message gos back to the queue for a retry. But in other cases it is dropped. Disable the status check `runner_enable_workflow_job_labels_check` was introduced together with introducing ephemeral runners. Since every event requires instance in the end. By enable the status check, no runner will be created. Since we cannot control which runner takes which job, events can cross.  Would be good to have a look at the logs for your scale-up lambda. 

In our case we have a small pool of runners, see the pool config. With the pool you can keep a small fleet of runners running based on a cron expressino. This to avoid jobs got stock, for messages that are not handled well.

So would suggest to enable the status check, and maybe run a pool instance based on a cron. 

About:
- deleay webhoo: was created once ephemeral runners was not supported at all, it keeps a message waiting on a queue for x seconds to give existing runners the time to start the job
