### ISSUE TITLE
Event match runner labels even though they're just a subset

### ISSUE THREAD

**Issue by ahamez** [philips-labs/terraform-aws-github-runner#2861]
When using the principal module (so, not the multi-runners one), I added the label `on-demand`:

```HCL
module "on_demand" {
  source  = "philips-labs/github-runner/aws"
  version = "v2.1.0"
  ...
  runner_extra_labels = "on-demand"
}
```

The Github workflow DOES NOT specify this label:
```yaml
...
jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
...
```

However, even though the workflow doesn't specify the `on-demand` label, a runner is started. When setting the log level to `debug`, we can see that the event does match the runner labels:

```
Received workflow job event with labels: '["self-hosted","Linux","X64"]'.
The event does match the runner labels: 'self-hosted,linux,x64,on-demand'
```

Is it an intended behaviour? 

If so, how can I restrict only some workflows to run the runners deployed by this module?
For instance, a use-case would be to run only some workflows on instances with a GPU.

If it matters, I use the org level setup. Also, I didn't change the value of `enable_runner_workflow_job_labels_check_all`, which defaults to `true`.

**Comment by npalm** [comment]
What you described in the issue should work, what means the job should not be accepted, And you are correct, the check label is by default true. The single runner is using internally the same matcher as the multi-runner. I have added a [test](https://github.com/philips-labs/terraform-aws-github-runner/pull/2881) to check the Issue. But the test is running fine. 

It could be still possible that there is a bug in the terraform config, since this is not checked in the unit test.

**Comment by ahamez** [comment]
If it helps, here's the full terraform definition:

```
# ----------------------------------------------------------------------------------------------- #

resource "random_id" "webhook_secret" {
  byte_length = 20
}

# ----------------------------------------------------------------------------------------------- #

module "on_demand" {
  source  = "philips-labs/github-runner/aws"
  version = "v2.1.0"

  aws_region = "eu-west-3"
  vpc_id     = var.vpcs["it-1"].vpc_id
  subnet_ids = var.vpcs["it-1"].private_subnets

  prefix = "github-runner-on-demand"

  ami_filter = {
    name = ["github-runner-on-demand-nogpu*"]
  }
  ami_owners = ["11111111111111"]

  github_app = {
    key_base64     = var.github_actions_on_demand_runner_pem
    id             = "XXXXXX"
    webhook_secret = random_id.webhook_secret.hex
  }

  instance_types = ["m5ad.2xlarge"]

  log_level                                   = "debug"
  enable_runner_workflow_job_labels_check_all = true
  runner_extra_labels                         = "on-demand"

  webhook_lambda_zip                = "./github_runner/lambdas/webhook.zip"
  runner_binaries_syncer_lambda_zip = "./github_runner/lambdas/runner-binaries-syncer.zip"
  runners_lambda_zip                = "./github_runner/lambdas/runners.zip"
  enable_organization_runners       = true
  # https://github.com/philips-labs/terraform-aws-github-runner/issues/1671
  pool_lambda_reserved_concurrent_executions = -1
  scale_up_reserved_concurrent_executions    = -1
}

# ----------------------------------------------------------------------------------------------- #
```

Is there something I can do to help resolve this?

**Comment by galz-cyera** [comment]
Also happened to me with multi runners config 

`[webhook:397be44f-a626-48ff-9ad9-b877ef66e7df index.js:90403  canRunJob] Received workflow job event with labels: '["self-hosted"]'. The event does match the runner labels: 'self-hosted,on-demand'`

**Comment by mcnicholls** [comment]
I'm also seeing the same with multi-runners.
I think I can see why...

When exact matching is turned on, it looks like the code is checking that every label the job specifies is matched by a runner label. However it doesn't check that every runner label is matched by a job label from what I can see.
So if your runner matches just specifies `self-hosted` with exact matching, then it will match the first runner config that includes `self-hosted`, regardless of the other labels it has.

What I was expecting was that it would match the labels exactly and check that both the job labels and the runner labels totally matched up. That way I could have a runner config that specifies some default labels (e.g. `self-hosted`, `x64`, `linux`) and it would be my catch all default for jobs that just specify those defaults.
I could then have more specialised runner configs that specify those defaults as well as extra labels.

Currently, depending on how i set exact match, the wrong runner is launched at the wrong time.
This is partly due to ordering as well, which is currently based on the exact match flag during sort, but I seem to be able to also influence it by changing the `id`. I would guess this is due to `multi_runner_config` being a map as the JavaScript sort looks to be preserving order beyond the exact match flag.


I think it all boils down to the intended meaning of the exact match flag.
Should it make sure all job labels are satisfied and trigger the first config it finds (current behaviour), or should it make sure that all job labels and runner labels match exactly and trigger the first config it finds?

**Comment by mattjegan** [comment]
I've also observed this behaviour. I'm using multi-runners and have a `self-hosted` runner and a `self-hosted-large` runner, both with labels that match the runner name and exactMatch turned on. I've been finding instances where a `self-hosted` job is scheduling a `self-hosted-large` runner and then my `self-hosted-large` jobs are never being picked up.
