### ISSUE TITLE
ephemeral jobs are scheduled on the terminated instance.

### ISSUE THREAD

**Issue by prashanthbgoud** [philips-labs/terraform-aws-github-runner#3013]
Hello All,

I see a strange issue, I am currently on 2.2.2 and I see some of the jobs are waiting for ever to start and when checked I see the instance on which the job is scheduled is already terminated.

We are using ephemeral runners.

```
Requested labels: self-hosted
Job defined at: xxxx/xxxxx/.github/workflows/pipeline.yml@refs/pull/78/merge
Waiting for a runner to pick up this job...
Job is about to start running on the runner: i-0fdeafa6993de8690 (organization)

```

on the runner I see below log line

`[2023-02-28 08:13:02Z INFO ProcessInvokerWrapper] Finished process 3271 with exit code 137, and elapsed time 00:00:00.0331364.`

**Comment by mattjegan** [comment]
@prashanthbgoud I saw a similar issue on 2.2.1 when using multi-runners. I had two labels `self-hosted` and `self-hosted-large` and when enqueuing a job for each it was possible that the `self-hosted-large` job would never be picked up because the smaller job would be picked up by the `self-hosted-large` instance. The fix was to make sure that `exactMatch=true` in my `matcherConfig`.
