### ISSUE TITLE
How to cut down on network traffic?

### ISSUE THREAD

**Issue by tedparagon** [philips-labs/terraform-aws-github-runner#3163]
I know this isn't strictly a question about this module but would appreciate any recommendations.

My runners generated over 6TB of BytesOutToSource on the NAT Gateway last month. I expect this to be almost entirely caused by the Docker images that are being pulled. I am in the process of switching that environment to NAT Instances to cut the costs. But I am also wondering if pulling the images during the AMI creation would also help somewhat?

Thanks!

**Comment by prashanthbgoud** [comment]
We have moved our runners to the public subnet to save costs incurred by NAT.

**Comment by strophy** [comment]
Last week I was facing a similar problem - after moving to AWS runners, Docker Hub rate limits were triggered. I deployed a Docker [Registry as a pull-through cache](https://docs.docker.com/registry/recipes/mirror/) which turned out to be fairly simple to set up. Maybe we can request this as a feature that can optionally be enabled? Where would I start to contribute a module that does that?

**Comment by strophy** [comment]
See [here for an implementation of the pull-through cache](https://github.com/dcginfra/tf-aws-gh-runner/blob/main/examples/platform/cache.tf) in terraform, used in a copy of the `prebuilt` example in this case. The prebuilt image includes a [directive that points docker at the cache instance](https://github.com/dcginfra/tf-aws-gh-runner/blob/main/images/ubuntu-jammy-platform/github_agent.ubuntu.pkr.hcl#L152) before trying Docker Hub.

**Comment by tedparagon** [comment]
Switching to [NAT Instances](https://github.com/int128/terraform-aws-nat-instance) saved us a ton of cost even though it didn't lower our network usage.

We are evaluating the pull-through caches now. In the meantime since our base Docker layers don't change that often I've also added some docker pulls when creating the AMI so those layers are already local. Definitely not ideal in long term but it did lower the traffic enough while we work on caching.

Thanks.

**Comment by GuptaNavdeep1983** [comment]
@tedparagon probably this, https://github.com/1debit/alternat is a better option for deploying and using NAT instances.

**Comment by sdarwin** [comment]
@strophy a pull-through registry cache is a must-have with busy GitHub runners since Docker Hub rate limits are set at a low level.    I would propose these enhancements:  
- instead of one cache, launch two small instances behind an internal load balancer for redundancy.
- proxy through a local nginx.   That opens the door to filtering and permission control. nginx has many capabilities and plain docker doesn't.  Users would be able to customize in the future when necessary.  Here's an example nginx file: https://github.com/cppalliance/ansible-docker-registry/blob/master/templates/registry.vhost.j2

> Where would I start to contribute a module that does that?

Submit a pull request in this repo.  Optionally chat with the maintainers first to find out if they will accept such a feature.

**Comment by strophy** [comment]
Thanks @sdarwin for the helpful pointers on how to design this! I've [added an ASG, ALB and SSM](https://github.com/dcginfra/tf-aws-gh-runner/blob/main/examples/platform/docker-cache.tf) Session Manager access to the pull-through cache, performance is great! Still a bit too uncertain of whether this is tidy enough (or even in the right place) so probably won't do a PR at the moment.
