### ISSUE TITLE
Hitting Github API Rate Limits

### ISSUE THREAD

**Issue by chasemgray** [philips-labs/terraform-aws-github-runner#3199]
Hi, we have a relatively high number of ephemeral runners, with a max runner count of 1-2K which goes up and down throughout the day. We have the scale-up handling most of the jobs, with a pool booting up a few hundred during peak times to pick up the work faster. 

We're starting to hit errors during peak times due to the Github API rate limits for the installed Github app. It seems that every machine launched retrieves its own token to register the runner with github, which can exhaust our API request limit when we have a lot of machines. An output of the error from Github is below. It seems that the token from Github has a lifetime of 1 hour. Is there a reason that each machine needs to request its own token? Is there anything else we can do to prevent this from occurring?

>message: 'API rate limit exceeded for installation ID XXXXXX.'
gh-ci-pool 'x-ratelimit-used': '15000',
gh-ci-pool 'x-ratelimit-resource': 'core',
gh-ci-pool 'x-ratelimit-reset': '1681944142',
gh-ci-pool 'x-ratelimit-remaining': '0',
gh-ci-pool 'x-ratelimit-limit': '15000'

**Comment by npalm** [comment]
@chasemgray would mind to have a direct chat via slack. Just discuss what we can improve here.

**Comment by chasemgray** [comment]
Sure, let me know which channel to join.

**Comment by velocibear** [comment]
Hey, we are seeing this as well and am curious if anything came from this discussion.

**Comment by npalm** [comment]
The problem 2 weeks ago was is mainly caused by problems on the AWS API for describe instances. Which bcomes very slow. From less than 1 second to over 30. Result messages back to the queue and more calls to GH. 

I agree for larger deployments this is a problem. GH APi is used for. Scaling up, pool and scaling down.
- List runners, to find number of registered and idle ones. 
- Check a job is still queued
- Create tokens

### Listening runners
Listing runners is required for
- Ensure not scaling up if the max is reached
- Ensure maintain a pool for ephemeral runners
- Find idle runners for scale down

### Check job
- Optional the job can be checked to decide if a new runner needs to be crated

### Register runner
For every runner we request a fresh token. Caching the token could be an option but would make it much more complex for repo level runners. Also we hope the token will be soon a one-time token which will improve the security.

## Limit API calls
The only option we have right now is
- run scale to less frequent
- don't check for the job

## Options

- Cache token, I don't like this approach due to complexity and security
- Use multiple apps round robbin for API calls. Also this is not quite easy since it requires you have to install the app in all the required repositories. For the webhook this won't be a big issue. 


## Help wanted
Any good idee or help here is welcome.

**Comment by guicaulada** [comment]
Hitting this as well.
