### ISSUE TITLE
v4.0.0 runner-group SSM parameter doesn't exist

### ISSUE THREAD

**Issue by tomiszili** [philips-labs/terraform-aws-github-runner#3391]
Hello,

I try to deploy the new v4.0.0 version and i got an error from the scale-up lambda function.
I/m using a pre-built AMI but i don't think this issue is related to the custom AMI.
```
{
    "level": "WARN",
    "message": "SSM Parameter \"/github-action-runners/github-actions-v4/runners/config/runner-group/Default\"\n         for Runner group Default does not exist",
    "service": "runners-scale-up",
    "timestamp": "2023-07-26T21:43:59.424Z",
    "xray_trace_id": "<IRRELEVANT>",
    "module": "scale-up",
    "region": "us-west-2",
    "environment": "github-actions-v4",
    "aws-request-id": "<IRRELEVANT>",
    "function-name": "github-actions-v4-scale-up",
    "runner": {
        "type": "Org",
        "owner": "<MASKED>"
    },
    "github": {
        "event": "workflow_job",
        "workflow_job_id": "15376683235"
    }
}
```
What is generating and creating this SSM parameter?
What am i doing wrong?

Thanks in advance.

**Comment by GuptaNavdeep1983** [comment]
This is not a blocking error and its just a warning. The scale up module will only log this warning first time and afterwards work fine because the code puts this SSM parameter if its not found first time. 

This strategy is used to avoid calls to GitHub to get the runner group id for the given runner group name. First the lambda checks if the runner group id is present in SSM parameter and if not, it queries the runner group id from GitHub and puts the value of it in the SSM parameter and for subsequent executions read this value from SSM parameter.

So as per this strategy you should not see this warning again other than for the first execution for a given runner group name.

There is an open issue to avoid this SSM call if the user passes a new proposed variable `runner_group_id` which can be submitted as a PR by the community.
