### ISSUE TITLE
Windows 2022 Full vs Core?

### ISSUE THREAD

**Issue by pcassaretto-cmc** [philips-labs/terraform-aws-github-runner#3423]
Is this the correct AMI https://github.com/philips-labs/terraform-aws-github-runner/blob/9d575b836b6e105ef898a524492dcc05e41dafcd/images/windows-core-2022/github_agent.windows.pkr.hcl#L86?

I get the impression this is Full edition vs core?  `Windows_Server-2022-English-Core-ECS_Optimized-*` returns AMIs for core?

**Comment by brodster2** [comment]
Would be good to get clarification if the switch from Windows core base AMI to Windows Full was intentional. https://github.com/philips-labs/terraform-aws-github-runner/commit/e3708c3cb74918306b463dd0da94dffb1cb75be8

**Comment by npalm** [comment]
The change was intentional, the change was initiated by change in licenses and polices. Which caused docker was not longer shipped with the AMI. Therefore in #3128 the AMI was changed. But it seems not reflected in the docs. Any improvement is welcome. Internally we build all our AMI's and not rely on the module defaults.

**Comment by brodster2** [comment]
I understand the reasoning around docker licencing, the question was more around why the pattern was updated from `Windows_Server-2022-English-Core-ContainersLatest-**` to `Windows_Server-2022-English-Full-ECS_Optimized-*` instead of `Windows_Server-2022-English-Core-ECS_Optimized-*`? I'm happy to raise a PR to change it, but I just wanted to make sure there wasn't a specific reason for using the windows Full AMI instead of Core.

**Comment by npalm** [comment]
@GuptaNavdeep1983 can you explain why we updated the pattern?

**Comment by GuptaNavdeep1983** [comment]
As per the [link](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-windows-ami-versions.html) provided by AWS , as replacement to previous AMI's, we can indeed use the Core images.

**Comment by sdarwin** [comment]
When getting this set up I tried both Core and Full images.  it turned out that Full was easier to debug, more reliable, you can install any windows packages whatsoever, everything works as expected, since it's a normal installation of windows.   Core seemed to present some difficulties, it might depend on what you are installing.

**Comment by npalm** [comment]
So let's make Full just the default. Anyone using the module can override the ami filter, or always build a custom AMI
