### ISSUE TITLE
Question: How can I set up self-hosting with MacOS?

### ISSUE THREAD

**Issue by aniespica** [philips-labs/terraform-aws-github-runner#3490]
We need to have the same setup as in Ubuntu, but on MacOS. This is because we do a lot of development in iOS and want to use some GitHub actions to check the developers' pull requests.

**Comment by npalm** [comment]
Currently mac is not supported. But could potentailly build in. The drawe back is that you have to clami hardward in AWS that is billed for 24 hours. On top of that clamied hardwar you can creat eec2 instances. (not concurrent, onlye one at the time). Only after 24 hours it makes sence to release tha radware since you are always mbillen for the first 24 horus. We are open to PR's that solveds this.
