### ISSUE TITLE
SSM Parameter Store: Use encryption for all parameters

### ISSUE THREAD

**Issue by thorstenthomsen** [philips-labs/terraform-aws-github-runner#4003]
Hi Team,
is it possible to use for all parameters in SSM Parameter Store encryption by using Typ SecureString?
I know that critical data are already encrypted but Security of my company will engage controls to have all parameters be encrypted, regardless of content.

Personal I am fine with the actual configuration but need to fullfill the requirements of my company security.

**Comment by npalm** [comment]
Thanks for reaching out. So far we only encrypted the "secret" values. Technically I see no problem with encrypting them all. However the impact could be huge, anyone having their own start script needs to rewrite them to fetch the secureString instead of the non ecnrypted one.

Can you share what the concern is of having the non-secured values not encrypted. Would it not just be teaching.

**Comment by npalm** [comment]
SSM parameters are used to for configuration of runners, and to inject the GitApp in the lambdas.

**Comment by thorstenthomsen** [comment]
Looks like that modify the runner start script will not be enaugh. The Webhook lambda will fetch the parameter /github-action-runners/gh-ci/webhook/runner-matcher-config in code. So I can't move all parameters to SecureString without modify lambda code. Is that correct?

**Comment by npalm** [comment]
You could give it a try. From the top of my head all code to fetch SSM is in a util module. So you need only to make changes in single place. The other place is the start script where you have to pass the securestring option as well when fetching.

**Comment by thorstenthomsen** [comment]
We are now use Github runner on Kubernetes cluster. Will close this issue.
