### ISSUE TITLE
runner-binaries-syncer Lambda Optional

### ISSUE THREAD

**Issue by mcaulifn** [philips-labs/terraform-aws-github-runner#605]
The `runner-binaries-syncer` lambda should be optional if using an AMI that bakes in the runner binary. 

The lambda would be created by default and not created if `sync_runner_binary` is set to `false`.

**Comment by rlove** [comment]
Do you trigger builds of your AMI when a new version is released?   Just curious how you plan to handle updates with AMI.

**Comment by mcaulifn** [comment]
Not quite sure yet. It will most likely be any of base AMI, tool, or runner binary.

**Comment by mcaulifn** [comment]
I was able to get the lambda and supporting resources optional but it requires removing the outputs from that module.

@npalm Do you see an issue with this approach?

**Comment by npalm** [comment]
@mcaulifn for me it is fine to make the syncer optional. As long the default keeps the syncer in place, since downloading the dist can be quit slow. Feel free to create a PR.  I do not prefer removing the outputs. Can you share your implementation so we can see how we can keep the output. I assume you use a count on the module? In that case a join with an empty output object should work.

**Comment by mcaulifn** [comment]
I could not get join to work as the outputs are maps. I'm probably doing something wrong.

I'll get a PR up shortly.

**Comment by ScottGuymer** [comment]
Was a PR ever created for this?
