### ISSUE TITLE
Possible Race Condition with ScaleUp and Simultaneous Workflows?

### ISSUE THREAD

**Issue by seorasray** [philips-labs/terraform-aws-github-runner#933]
I saw some odd behaviour with 0.14.0 today:

Github Repo with 3 Workflows that trigger at the same time used 1 existing instance and only spun up 1 new instance. Looking at the details it appears as if the following happened:

Workflow 1 arrives at ScaleUp, existing idle runner picks it up so status != queued and ScaleUp logs it but takes no action.
... time passes ...
Workflow 2 arrives at ScaleUp, ScaleUp sees status == queued so logs and spins up new instance.
... time passes ...
Newly spun up instances picks up queued workflow, 3
... time passes ...
Workflow 3 arrives at ScaleUp, ScaleUp sees status != queued so logs and takes no action.

At this point Workflow 2 is still sitting there queued since the instance that was supposed to run it is now running 3.

Not sure if this is a known issue, problem with my config or a bug.

Thanks for the awesome project!

**Comment by npalm** [comment]
Actually it is a fact of the the design of the runner setup. We assume that an idle runner wil pickup any idle build shorty. In other words will not remain idle. But we can not control which jobs it takes first. We haven't change anything recently in the scaling strategy. So it sounds not logically that it is related to the upgrade to 0.14

Your conclussion that the instances that was supossed to run workflow 2 is running 3 is not correct. We just scale at the moment a workflow is in the status queued. You can configure the time between the event arrives and the system scale up, this results that the message is kept longer on the SQS queue. Once the message is read by the scale up lambda we simply check if the corrolated job is queued or not. If queued and the max is not reached we scale up. Otherwise we drop the message. Once the system decide to scale up, we assume the workflow will run on **any** of the running instnaces. So if workflow 1 is a short one it could be even that workflow 2 will run on the first runner. 

Even you have any suggestion / ideas to improve the setup feel free to suggest another the design or rasie a PR. It seems GitHub is working on events per job containing the runner name. This should make it possible to scale more fine grained.
